language: android
dist: trusty

android: 
  components: 
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

script:
  - ./gradlew cleanTest test --stacktrace

deploy:
  - provider: script
    script: MAVEN_REPO_URL="https://api.bintray.com/maven/americanexpress/maven/io.americanexpress.busybee/;publish=0" ./gradlew build publish -Dsnapshot=false --stacktrace
    on:
      tags: true
  - provider: script
    script: MAVEN_REPO_URL="https://oss.jfrog.org/artifactory/oss-snapshot-local/" ./gradlew build publish --stacktrace
    on:
      branches: "master"

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.android/build-cache