language: android
dist: trusty

android: 
  components: 
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-29

script:
  - ./gradlew cleanTest test --stacktrace

deploy:
  - provider: script
    script: ./gradlew build publish -Dsnapshot=false --stacktrace
    on:
      tags: true
  - provider: script
    script: ./gradlew build publish --stacktrace
    on:
      branch: master

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.android/build-cache