version: 2.1

executors:
  android-api29:
    docker:
      # https://hub.docker.com/layers/circleci/android/api-29/images/sha256-9fc0f34301182ba3730b1ca085e827927675168e57d412f6cc86256c7cd28e2d
      #  api-29, JDK 11.0.10, commandlinetools-linux-6609375_latest.zip
      - image: circleci/android@sha256:9fc0f34301182ba3730b1ca085e827927675168e57d412f6cc86256c7cd28e2d


anchors:
  - &common_job_config
    executor: android-api29


jobs:
  test:
    <<: *common_job_config
    steps:
      # TODO: need to merge with destination branch before building
      - checkout
      - run:
          name: gradle test
          command: ./gradlew cleanTest test --stacktrace

  publish-snapshot:
    <<: *common_job_config
    steps:
      - checkout
      - run:
          name: Publish -SNAPSHOT
          command: MAVEN_REPO_URL="https://s01.oss.sonatype.org/content/repositories/snapshots/" ./gradlew build publish --stacktrace

  publish-release:
    <<: *common_job_config
    steps:
      - checkout
      - run:
          name: Publish Release
          command: MAVEN_REPO_URL="https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/" ./gradlew build publish -Dsnapshot=false --stacktrace


workflows_setup:
  - &context
    context:
      - maven_central_credentials
      - code_signing_credentials

  - &default_branch
      "main"

workflows:
  pull_request_workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore: *default_branch

  default_branch_workflow:
    when:
      # TODO: publish -SNAPSHOT for branches with branch name in the version
      equal: [ *default_branch, << pipeline.git.branch >> ]
    jobs:
      - test
      - publish-snapshot:
          <<: [ *context ]
          requires:
            - test


  publish_release:
    jobs:
      - publish-release:
          <<: [ *context ]
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
